services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672  # Protocolo AMQP
      - 15672:15672  # Host para management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
